language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false

node_js:
  - '9'
  - '8'
  - '6'
  - '4'

after_success:
  - npm run semantic-release
  - npm run coverage:uplaod

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/
