name: Test
"on":
  push:
    branches:
      - dependabot/npm_and_yarn/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 10
          - 12
          - 14
    name: Node ${{ matrix.node }} 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test

  # separate job to set as required in branch protection,
  # as the above change each time the Node versions change
  validate-types:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: "npm run validate:ts"
