name: Update
on:
  repository_dispatch:
    # https://github.com/apps/octokit-release-notifier
    types: [octokit/webhooks release]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - run: npm ci
      - uses: gr2m/await-npm-package-version-action@v1
        with:
          package: "@octokit/webhooks-schemas"
          version: ${{ github.event.client_payload.release.tag_name }}
      - run: npm install --save-exact --save-dev @octokit/webhooks-schemas@latest
      - uses: gr2m/await-npm-package-version-action@v1
        with:
          package: "@octokit/webhooks-types"
          version: ${{ github.event.client_payload.release.tag_name }}
      - run: npm install --save-exact @octokit/webhooks-types@latest
      - run: npm run generate-types
      - name: create pull request
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: "${{ secrets.OCTOKITBOT_PAT }}"
        with:
          title: "\U0001F6A7 \U0001F916\U0001F4EF Webhooks changed"
          body: "A new release of [@octokit/webhooks-definitions](https://github.com/octokit/webhooks) was just released \U0001F44B\U0001F916\n\nThis pull request updates the TypeScript definitions derived from `@octokit/webhooks-definitions`. I can't tell if the changes are fixes, features or breaking, you'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/openapi/blob/main/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).\n"
          branch: "update-octokit-webhooks"
          author: Octokit Bot <octokitbot@martynus.net>
          commit-message: "WIP: Webhooks changed - please review"
          labels: "maintenance"
